version: '2'
services:
  mes-data-replication-service-e2e-mysql:
    image: mysql:5.7
    container_name: mes-data-replication-service-e2e-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pa55word1
  mes-data-replication-service-e2e-migration:
    build: .
    container_name: mes-data-replication-service-e2e-migration
    depends_on:
      - mes-data-replication-service-e2e-mysql
