CREATE USER IF NOT EXISTS 'refdata' IDENTIFIED WITH mysql_native_password BY '<USER_PASSWORD>' PASSWORD EXPIRE NEVER;
GRANT SELECT ON tarsreplica.TEST_CENTRE TO 'refdata';
GRANT SELECT ON tarsreplica.TEST_CENTRE_NAME TO 'refdata';
