import { ScheduleBookingsConfig } from '@dvsa/des-scheduling-config/build/scheduling-schema';
import type {
  Gender,
  PreviousCancellation,
  SpecialNeedsCode,
  VehicleGearbox,
  VehicleTypeCode,
} from '@dvsa/mes-journal-schema';
import { customDurationMetric, error, info } from '@dvsa/mes-microservice-common/application/utils/logger';
import { and, gte, inArray, lte } from 'drizzle-orm';
import { mysqlTable } from 'drizzle-orm/mysql-core';
import { drizzle, type MySql2Database } from 'drizzle-orm/mysql2/driver';
import { eq } from 'drizzle-orm/sql/expressions/conditions';
import * as moment from 'moment';
import type * as mysql from 'mysql2';
import type { ExaminerRecord } from '../../../domain/examiner-record';
import type { ExaminerTestSlot } from '../../../domain/examiner-test-slot';
import { getMockDSPBookings } from './__mocks__/test-slot.mock';

type Category =
  | 'A'
  | 'A1'
  | 'A1M1'
  | 'A1M2'
  | 'A2'
  | 'A2M1'
  | 'A2M2'
  | 'ADI2'
  | 'ADI3'
  | 'AM1'
  | 'AM2'
  | 'B'
  | 'B+E'
  | 'B+E MMA'
  | 'B1'
  | 'BTRIAL'
  | 'C'
  | 'C+E'
  | 'C+EM'
  | 'C1'
  | 'C1+E'
  | 'C1+EM'
  | 'C1M'
  | 'CCPC'
  | 'CM'
  | 'D'
  | 'D+E'
  | 'D+EM'
  | 'D1'
  | 'D1+E'
  | 'D1+EM'
  | 'D1M'
  | 'DCPC'
  | 'DE A1M1'
  | 'DE A1M2'
  | 'DE A2M1'
  | 'DE A2M2'
  | 'DE AM1'
  | 'DE AM2'
  | 'DE B'
  | 'DE C'
  | 'DE C+E'
  | 'DE C1'
  | 'DE C1+E'
  | 'DE D'
  | 'DE D+E'
  | 'DE D1'
  | 'DE D1+E'
  | 'DE M4 B'
  | 'DE M4 L'
  | 'DE PM1'
  | 'DE PM2'
  | 'DEM3'
  | 'DEM4'
  | 'DM'
  | 'EUA1M1'
  | 'EUA1M2'
  | 'EUA2M1'
  | 'EUA2M2'
  | 'EUAM1'
  | 'EUAM2'
  | 'EUAMM1'
  | 'EUAMM2'
  | 'F'
  | 'G'
  | 'H'
  | 'K'
  | 'O'
  | 'P'
  | 'PM1'
  | 'PM2'
  | 'SC'
  | 'Z'
  | 'Z1'
  | 'Z2';

export interface ScheduleBookingsRow {
  id: bigint;
  bookingReference: string;
  examinerStaffNumber: string;
  testslotStart: Date;
  testslotDurationMinutes: number;
  testslotVehicleTypeCode: VehicleTypeCode;
  testslotVehicleSlotTypeCode: number | null;
  testcentreName: string;
  testcentreCostCode: string;
  candidateTitle: string;
  candidateFirstName: string;
  candidateSecondName: string;
  candidateThirdName: string;
  candidateLastName: string;
  candidateDriverNumber: string;
  candidateDateOfBirth: Date;
  candidateGender: Gender;
  candidateAddressLine1: string;
  candidateAddressLine2: string;
  candidateAddressLine3: string;
  candidateAddressLine4: string;
  candidateAddressLine5: string;
  candidatePostcode: string;
  candidatePrimaryTelephone: string;
  candidateSecondaryTelephone: string;
  candidateMobileTelephone: string;
  candidateEmailAddress: string;
  candidatePrn: number | null;
  candidatePreviousADITests: number | null;
  candidateEthnicityCode: string | null;
  applicationWelshTest: number;
  applicationExtendedTest: number;
  applicationMeetingPlace: string;
  applicationProgressiveAccess: number;
  applicationSpecialNeeds: string;
  applicationSpecialNeedsExtTest: number;
  applicationSpecialNeedsCode: SpecialNeedsCode;
  applicationEntitlementCheck: number;
  applicationFitMarker: number;
  applicationFitCaseNumber: string;
  applicationCategoryEntitlementCheck: number;
  applicationVehicleSeats: number | null;
  applicationVehicleHeight: string | null;
  applicationVehicleWidth: string | null;
  applicationVehicleLength: string | null;
  applicationTestCategory: Category;
  applicationVehicleGearbox: VehicleGearbox;
  previousCancellation: PreviousCancellation | null;
  businessId: number | null;
  businessName: string | null;
  businessAddressLine1: string | null;
  businessAddressLine2: string | null;
  businessAddressLine3: string | null;
  businessAddressLine4: string | null;
  businessAddressLine5: string | null;
  businessPostcode: string | null;
  businessTelephone: string | null;
  examinerVisiting: number | null;
}

/** Convert UTC datetime value from scheduling DB into local datetime for the journal. This is required for consistency with how TARS data is written to the journal */
const toUK = (uTCString: string) => {
  const isoNoTZ = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/;

  if (!isoNoTZ.test(uTCString)) return uTCString;

  return new Date(uTCString + 'Z')
    .toLocaleString('sv-SE', {
      timeZone: 'Europe/London',
      hour12: false,
    })
    .replace(' ', 'T');
};

/** Recursively removes nulls or undefined values from results to match the format generated by TARS' SQL statement*/
const stripNulls = (value: any): any => {
  // If the value is null or undefined, remove it
  if (value === null || value === undefined) return undefined;

  // If the value is an empty array, remove it
  if (Array.isArray(value)) {
    return value.length ? value : undefined;
  }

  // If the trimmed value is an empty string, remove it
  if (typeof value === 'string') {
    return value.trim().length ? value : undefined;
  }

  // If the value is an object, run this function recursively on its properties to remove all null values from it
  if (typeof value === 'object') {
    // Strip nulls from object properties
    const entries = Object.entries(value)
      .map(([k, v]) => [k, stripNulls(v)] as [string, any])
      .filter(([, v]) => v !== undefined);
    if (!entries.length) return undefined;
    return Object.fromEntries(entries);
  }

  return value;
};

/**
 * Get all detailed test slots, for the specified time window.
 * @param connectionPool
 * @param examinerRecords
 * @param journalStartDate The start date of the time window
 * @param endDate The end date of the time window
 * @returns The detailed test slots
 */

export const getDSPTestSlots = async (
  connectionPool: mysql.Pool,
  examinerRecords: ExaminerRecord[],
  journalStartDate: Date,
  endDate: Date
): Promise<ExaminerTestSlot[]> => {
  try {
    const db: MySql2Database = drizzle(connectionPool);

    const windowStart = moment(journalStartDate).toDate();
    const windowEnd = moment(endDate).toDate();

    info(`Start run - running DSP test DES slots query from ${windowStart} to ${windowEnd}`);
    const start = new Date();

    const ScheduleBookings = mysqlTable('bookings', ScheduleBookingsConfig);

    const drizzleBookingQuery = db
      .select({
        id: ScheduleBookings.id,
        examinerStaffNumber: ScheduleBookings.examiner_staff_number,
        bookingReference: ScheduleBookings.booking_reference,

        testslotStart: ScheduleBookings.testslot_start,
        testslotDurationMinutes: ScheduleBookings.testslot_duration_minutes,
        testslotVehicleTypeCode: ScheduleBookings.testslot_vehicle_type_code,
        testslotVehicleSlotTypeCode: ScheduleBookings.testslot_vehicle_slot_type_code,
        testcentreName: ScheduleBookings.testcentre_name,
        testcentreCostCode: ScheduleBookings.testcentre_cost_code,

        applicationEntitlementCheck: ScheduleBookings.application_entitlement_check,
        applicationExtendedTest: ScheduleBookings.application_extended_test,
        applicationFitMarker: ScheduleBookings.application_fit_marker,
        applicationFitCaseNumber: ScheduleBookings.application_fit_case_number,
        applicationProgressiveAccess: ScheduleBookings.application_progressive_access,
        applicationSpecialNeeds: ScheduleBookings.application_special_needs,
        applicationSpecialNeedsCode: ScheduleBookings.application_special_needs_code,
        applicationSpecialNeedsExtTest: ScheduleBookings.application_special_needs_ext_test,
        applicationTestCategory: ScheduleBookings.application_test_category,
        applicationVehicleGearbox: ScheduleBookings.application_vehicle_gearbox,
        applicationWelshTest: ScheduleBookings.application_welsh_test,
        applicationMeetingPlace: ScheduleBookings.application_meeting_place,
        applicationCategoryEntitlementCheck: ScheduleBookings.application_category_entitlement_check,
        applicationVehicleSeats: ScheduleBookings.application_vehicle_seats,
        applicationVehicleHeight: ScheduleBookings.application_vehicle_height_m,
        applicationVehicleWidth: ScheduleBookings.application_vehicle_width_m,
        applicationVehicleLength: ScheduleBookings.application_vehicle_length_m,
        candidateAddressLine1: ScheduleBookings.candidate_address_line1,
        candidateAddressLine2: ScheduleBookings.candidate_address_line2,
        candidateAddressLine3: ScheduleBookings.candidate_address_line3,
        candidateAddressLine4: ScheduleBookings.candidate_address_line4,
        candidateAddressLine5: ScheduleBookings.candidate_address_line5,
        candidatePostcode: ScheduleBookings.candidate_postcode,
        candidateFirstName: ScheduleBookings.candidate_first_name,
        candidateSecondName: ScheduleBookings.candidate_second_name,
        candidateThirdName: ScheduleBookings.candidate_third_name,
        candidateLastName: ScheduleBookings.candidate_last_name,
        candidateTitle: ScheduleBookings.candidate_title,
        candidateDriverNumber: ScheduleBookings.candidate_driver_number,
        candidateMobileTelephone: ScheduleBookings.candidate_mobile_telephone,
        candidateEmailAddress: ScheduleBookings.candidate_email_address,
        candidatePrn: ScheduleBookings.candidate_prn,
        candidatePreviousADITests: ScheduleBookings.candidate_previous_adi_tests,
        candidatePrimaryTelephone: ScheduleBookings.candidate_primary_telephone,
        candidateSecondaryTelephone: ScheduleBookings.candidate_secondary_telephone,
        candidateDateOfBirth: ScheduleBookings.candidate_date_of_birth,
        candidateEthnicityCode: ScheduleBookings.candidate_ethnicity_code,
        candidateGender: ScheduleBookings.candidate_gender,

        businessId: ScheduleBookings.business_id,
        businessName: ScheduleBookings.business_name,
        businessAddressLine1: ScheduleBookings.business_address_line1,
        businessAddressLine2: ScheduleBookings.business_address_line2,
        businessAddressLine3: ScheduleBookings.business_address_line3,
        businessAddressLine4: ScheduleBookings.business_address_line4,
        businessAddressLine5: ScheduleBookings.business_address_line5,
        businessPostcode: ScheduleBookings.business_postcode,
        businessTelephone: ScheduleBookings.business_telephone,

        previousCancellation: ScheduleBookings.previous_cancellation,

        examinerVisiting: ScheduleBookings.examiner_visiting,
      })
      .from(ScheduleBookings)
      .where(
        and(
          eq(ScheduleBookings.marked_for_deletion, 0),
          inArray(
            ScheduleBookings.examiner_staff_number,
            examinerRecords.map((id) => id.staff_number)
          ),
          gte(ScheduleBookings.testslot_start, windowStart),
          lte(ScheduleBookings.testslot_start, windowEnd)
        )
      );

    let rows: ScheduleBookingsRow[] = (await drizzleBookingQuery) as ScheduleBookingsRow[];

    if (process.env.ADD_MOCK_DSP_BOOKINGS === 'true') {
      info(`running mock DSP Bookings from ${windowStart} to ${windowEnd}`);
      // Combine the fake data with the real data
      rows = [
        ...rows,
        ...(await getMockDSPBookings(
          examinerRecords.map((id) => Number(id.staff_number)),
          new Date(windowEnd),
          new Date(windowStart)
        )),
      ];
    }

    info('DES Slots query returned rows:', rows.length);
    const results: ExaminerTestSlot[] = rows.map((r: ScheduleBookingsRow): ExaminerTestSlot => {
      const mappedData: ExaminerTestSlot = {
        examinerId: examinerRecords.find((record: ExaminerRecord) => record.staff_number === r.examinerStaffNumber)
          .individual_id,
        testSlot: {
          slotDetail: {
            slotId: r.id != null ? Number(r.id) : undefined,
            start: r.testslotStart ? toUK(moment(r.testslotStart).format('YYYY-MM-DDTHH:mm:ss')) : undefined,
            duration: r.testslotDurationMinutes != null ? Number(r.testslotDurationMinutes) : undefined,
          },
          vehicleTypeCode: r.testslotVehicleTypeCode,
          vehicleSlotTypeCode:
            r.testslotVehicleSlotTypeCode != null ? Number(r.testslotVehicleSlotTypeCode) : undefined,
          testCentre: {
            centreName: r.testcentreName,
            costCode: r.testcentreCostCode,
          },
          booking: {
            candidate: {
              candidateId: undefined,
              candidateName: {
                firstName: r.candidateFirstName,
                secondName: r.candidateSecondName,
                thirdName: r.candidateThirdName,
                lastName: r.candidateLastName,
                title: r.candidateTitle,
              },
              driverNumber: r.candidateDriverNumber,
              dateOfBirth: r.candidateDateOfBirth ? moment(r.candidateDateOfBirth).format('YYYY-MM-DD') : undefined,
              gender: r.candidateGender,
              candidateAddress: {
                addressLine1: r.candidateAddressLine1,
                addressLine2: r.candidateAddressLine2,
                addressLine3: r.candidateAddressLine3,
                addressLine4: r.candidateAddressLine4,
                addressLine5: r.candidateAddressLine5,
                postcode: r.candidatePostcode,
              },
              primaryTelephone: r.candidatePrimaryTelephone,
              secondaryTelephone: r.candidateSecondaryTelephone,
              mobileTelephone: r.candidateMobileTelephone,
              emailAddress: r.candidateEmailAddress,
              prn: r.candidatePrn,
              previousADITests: r.candidatePreviousADITests,
              ethnicityCode: r.candidateEthnicityCode,
            },
            application: {
              bookingReference: r.bookingReference,
              welshTest: Boolean(r.applicationWelshTest),
              extendedTest: Boolean(r.applicationExtendedTest),
              meetingPlace: r.applicationMeetingPlace,
              progressiveAccess: Boolean(r.applicationProgressiveAccess),
              specialNeeds: r.applicationSpecialNeeds,
              specialNeedsExtendedTest: Boolean(r.applicationSpecialNeedsExtTest),
              specialNeedsCode: r.applicationSpecialNeedsCode,
              entitlementCheck: Boolean(r.applicationEntitlementCheck),
              fitMarker: Boolean(r.applicationFitMarker),
              fitCaseNumber: r.applicationFitCaseNumber,
              categoryEntitlementCheck: Boolean(r.applicationCategoryEntitlementCheck),
              vehicleSeats: r.applicationVehicleSeats,
              vehicleHeight: r.applicationVehicleHeight != null ? Number(r.applicationVehicleHeight) : undefined,
              vehicleWidth: r.applicationVehicleWidth != null ? Number(r.applicationVehicleWidth) : undefined,
              vehicleLength: r.applicationVehicleLength != null ? Number(r.applicationVehicleLength) : undefined,
              testCategory: r.applicationTestCategory,
              vehicleGearbox: r.applicationVehicleGearbox,
            },
            previousCancellation: r.previousCancellation,
            business: {
              businessId: r.businessId,
              businessName: r.businessName,
              businessAddress: {
                addressLine1: r.businessAddressLine1,
                addressLine2: r.businessAddressLine2,
                addressLine3: r.businessAddressLine3,
                addressLine4: r.businessAddressLine4,
                addressLine5: r.businessAddressLine5,
                postcode: r.businessPostcode,
              },
              telephone: r.businessTelephone,
            },
          },
          examinerVisiting: Boolean(r.examinerVisiting),
        },
      };
      return stripNulls(mappedData) as ExaminerTestSlot;
    });

    const end = new Date();
    info(`Finished run - DSP test slots - ${results.length} test slots loaded and mapped`);
    customDurationMetric('DESTestSlotsQuery', 'Time taken querying detailed test slots, in seconds', start, end);
    return results;
  } catch (err) {
    error('Error in getDSPTestSlots: ', err);
    return [];
  }
};
