version: '2'
services:
  mes-data-replication-service-e2e-mysql:
    image: mysql:5.7
    container_name: mes-data-replication-service-e2e-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pa55word1
    volumes:
      - ../destination-db/database-objects/010_createTables.sql:/docker-entrypoint-initdb.d/010_createTables.sql
      - ../destination-db/database-objects/020_createViews.sql:/docker-entrypoint-initdb.d/020_createViews.sql
      - ../destination-db/database-objects/030_createIndexes.sql:/docker-entrypoint-initdb.d/030_createIndexes.sql
      - ../destination-db/database-objects/040_createFunctions.sql:/docker-entrypoint-initdb.d/040_createFunctions.sql
      - ../destination-db/sample-data-load/1010_Create_uspGenerateExaminerData.sql:/docker-entrypoint-initdb.d/1010_Create_uspGenerateExaminerData.sql
      - ../destination-db/sample-data-load/1020_Create_uspGenerateJournalData.sql:/docker-entrypoint-initdb.d/1020_Create_uspGenerateJournalData.sql
      - ../destination-db/sample-data-load/1030_GenerateCalendarData.sql:/docker-entrypoint-initdb.d/1030_GenerateCalendarData.sql
      - ../destination-db/sample-data-load/1040_GenerateReferenceData.sql:/docker-entrypoint-initdb.d/1040_GenerateReferenceData.sql
      - ../destination-db/sample-data-load/1050_ClearDownTestData.sql:/docker-entrypoint-initdb.d/1050_ClearDownTestData.sql
      - ../destination-db/sample-data-load/1060_JournalTestData_01234567_CatB_2Days.sql:/docker-entrypoint-initdb.d/1060_JournalTestData_01234567_CatB_2Days.sql
      - ../destination-db/sample-data-load/1070_JournalTestData_00123456_VariousCat_1Day.sql:/docker-entrypoint-initdb.d/1070_JournalTestData_00123456_VariousCat_1Day.sql