import { ExaminerTestSlot } from '../../../../domain/examiner-test-slot';
import * as moment from 'moment/moment';

export const TARSTestSlotMock = (examinerId: number[], testSlotRun: number): ExaminerTestSlot[] => {
  const bookings: ExaminerTestSlot[] = [
    {
      examinerId: 1,
      testSlot: {
        booking: {
          application: {
            applicationId: Number(`1${testSlotRun}`),
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            fitMarker: true,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B',
            vehicleGearbox: 'Automatic',
            welshTest: false,
            meetingPlace: 'Test Meeting Place.',
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: 'Address Line 1',
              addressLine2: 'Address Line 2',
              addressLine3: 'Address Line 3',
              addressLine4: 'Address Line 4',
              addressLine5: 'Address Line 5',
              postcode: 'PO57 0DE',
            },
            candidateId: 9000,
            candidateName: {
              firstName: 'Firstname',
              lastName: 'Surname',
              title: 'Title',
            },
            driverNumber: 'SURNA123456789DO',
            mobileTelephone: '07111 123456',
            primaryTelephone: '01234 567890',
            secondaryTelephone: '04321 098765',
            dateOfBirth: '1977-07-02',
            ethnicityCode: 'D',
            gender: 'F',
          },
          previousCancellation: [
            'Act of nature',
          ],
        },
        slotDetail: {
          duration: 57,
          slotId: 1000,
          start: moment(Date.now()).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 1,
          centreName: 'Test Centre 1',
          costCode: 'TC1',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345600,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B',
            vehicleGearbox: 'Manual',
            welshTest: false,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '33 Montgomery Street',
              addressLine2: 'Coventry Road',
              addressLine3: 'Fuller Place',
              addressLine4: 'Salix',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 100,
            candidateName: {
              firstName: 'Alisa',
              lastName: 'Garza',
              title: 'Ms',
            },
            driverNumber: 'CATBA123456789DO',
            mobileTelephone: '(936) 552-2157',
            primaryTelephone: '(882) 408-3344',
            emailAddress: 'mobexaminer@gmail.com',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'M',
          },
          previousCancellation: [
            'Act of nature',
          ],
        },
        slotDetail: {
          duration: 57,
          slotId: 4299,
          start: moment().set({hour: 7, minute: 50, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),

        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345611,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B+E',
            vehicleGearbox: 'Automatic',
            welshTest: false,
            vehicleHeight: 3.5,
            vehicleWidth: 4,
            vehicleLength: 6,
            vehicleSeats: 3,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '54',
              addressLine2: 'Commerce Street',
              addressLine3: 'Crystal Street',
              addressLine4: 'Bancroft',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 6289,
            candidateName: {
              firstName: 'Osborne',
              lastName: 'Wolfe',
              title: 'Mr',
            },
            driverNumber: 'CATY123456789D01',
            mobileTelephone: '(893) 567-2537',
            primaryTelephone: '(936) 443-2201',
            secondaryTelephone: '(915) 417-3960',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'F',
          },
          business: {
            businessAddress: {
              addressLine1: '36 B+E',
              addressLine2: 'Sackett Street',
              addressLine3: 'Suriname',
              postcode: 'SA73 0TT',
            },
            businessId: 2908,
            businessName: 'Applideck',
            telephone: '(905) 597-2433',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 7364,
          start: moment().set({hour: 8, minute: 45, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345622,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'C',
            vehicleGearbox: 'Manual',
            welshTest: false,
            meetingPlace: 'Meet me at the Xymonk pub in Alamo',
            vehicleHeight: 4,
            vehicleWidth: 5.5,
            vehicleLength: 8,
            vehicleSeats: 8,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '57 Furman Street',
              addressLine2: 'Rapelye Street',
              addressLine3: 'Halsey Street',
              addressLine4: 'Dale',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 3290,
            candidateName: {
              firstName: 'Shirley',
              lastName: 'Benton',
              title: 'Ms',
            },
            driverNumber: 'CATCA123456789DO',
            mobileTelephone: '(967) 506-3388',
            primaryTelephone: '(888) 525-3094',
            secondaryTelephone: '(930) 445-3382',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'F',
          },
          business: {
            businessAddress: {
              addressLine1: '53 B+E',
              addressLine2: 'Cumberland Walk',
              addressLine3: 'Greece',
              postcode: 'SA73 0TT',
            },
            businessId: 983,
            businessName: 'Zolarity',
            telephone: '(881) 460-2794',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 3703,
          start: moment().set({hour: 9, minute: 44, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345633,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'C',
            vehicleGearbox: 'Manual',
            welshTest: false,
            vehicleHeight: 4.5,
            vehicleWidth: 4.5,
            vehicleLength: 14,
            vehicleSeats: 4,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '55 Pierrepont Street',
              addressLine2: 'Clifford Place',
              addressLine3: 'Provost Street',
              addressLine4: 'Bascom',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 3200,
            candidateName: {
              firstName: 'Fox',
              lastName: 'Farrell',
              title: 'Dr',
            },
            driverNumber: 'CATCB123456789DO',
            mobileTelephone: '(999) 454-3317',
            primaryTelephone: '(805) 405-2289',
            emailAddress: 'mobexaminer@gmail.com',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'M',
          },
          previousCancellation: [
            'Act of nature',
          ],
        },
        slotDetail: {
          duration: 112,
          slotId: 6003,
          start: moment().set({hour: 10, minute: 44, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345644,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B+E',
            vehicleGearbox: 'Automatic',
            welshTest: false,
            vehicleHeight: 3.5,
            vehicleWidth: 6,
            vehicleLength: 5,
            vehicleSeats: 3,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '33',
              addressLine2: 'Albemarle Road',
              addressLine3: 'Joralemon Street',
              addressLine4: 'Malo',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 3697,
            candidateName: {
              firstName: 'Sheila',
              lastName: 'Kirk',
              title: 'Miss',
            },
            driverNumber: 'CATY123456789D02',
            mobileTelephone: '(867) 566-2487',
            primaryTelephone: '(846) 570-3936',
            secondaryTelephone: '(899) 457-3249',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'M',
          },
          business: {
            businessAddress: {
              addressLine1: '42 B+E',
              addressLine2: 'Walker Court',
              addressLine3: 'Armenia',
              postcode: 'SA73 0TT',
            },
            businessId: 3410,
            businessName: 'Duflex',
            telephone: '(888) 491-2147',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 7942,
          start: moment().set({hour: 13, minute: 22, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345655,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B',
            vehicleGearbox: 'Manual',
            welshTest: true,
            meetingPlace: 'Meet me at the Zboo pub in Lookingglass',
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '34 Bushwick Court',
              addressLine2: 'Junius Street',
              addressLine3: 'Chestnut Avenue',
              addressLine4: 'Konterra',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 8885,
            candidateName: {
              firstName: 'Morales',
              lastName: 'Osborn',
              title: 'Mr',
            },
            driverNumber: 'CATBB123456789DO',
            mobileTelephone: '(850) 548-2508',
            primaryTelephone: '(893) 491-3307',
            secondaryTelephone: '(839) 434-3070',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'M',
          },
          business: {
            businessAddress: {
              addressLine1: '27 B+E',
              addressLine2: 'Ruby Street',
              addressLine3: 'Guinea-Bissau',
              postcode: 'SA73 0TT',
            },
            businessId: 7181,
            businessName: 'Austech',
            telephone: '(889) 512-3214',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 5428,
          start: moment().set({hour: 14, minute: 20, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345666,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B+E',
            vehicleGearbox: 'Automatic',
            welshTest: false,
            vehicleHeight: 2.5,
            vehicleWidth: 5,
            vehicleLength: 16,
            vehicleSeats: 5,
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '27',
              addressLine2: 'Howard Place',
              addressLine3: 'Bragg Court',
              addressLine4: 'Hartsville/Hartley',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 3513,
            candidateName: {
              firstName: 'Bessie',
              lastName: 'Walls',
              title: 'Ms',
            },
            driverNumber: 'CATY123456789D03',
            mobileTelephone: '(972) 530-3148',
            primaryTelephone: '(880) 583-3566',
            secondaryTelephone: '(824) 537-2308',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'F',
          },
          business: {
            businessAddress: {
              addressLine1: '32 B+E',
              addressLine2: 'Highlawn Avenue',
              addressLine3: 'Congo',
              postcode: 'SA73 0TT',
            },
            businessId: 7314,
            businessName: 'Surelogic',
            telephone: '(953) 541-2090',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 5752,
          start: moment().set({hour: 15, minute: 18, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
    {
      examinerId: 9000005,
      testSlot: {
        booking: {
          application: {
            applicationId: 72345677,
            bookingSequence: 1,
            checkDigit: 1,
            entitlementCheck: false,
            extendedTest: false,
            progressiveAccess: false,
            specialNeedsCode: 'NONE',
            specialNeedsExtendedTest: false,
            testCategory: 'B',
            vehicleGearbox: 'Manual',
            welshTest: true,
            meetingPlace: 'Meet me at the Kog pub in Waverly',
            categoryEntitlementCheck: false,
          },
          candidate: {
            candidateAddress: {
              addressLine1: '40 Celeste Court',
              addressLine2: 'Boynton Place',
              addressLine3: 'Fillmore Avenue',
              addressLine4: 'Beaulieu',
              addressLine5: 'Address Line 5',
              postcode: 'BR82 0DE',
            },
            candidateId: 3641,
            candidateName: {
              firstName: 'Ramsey',
              lastName: 'Zimmerman',
              title: 'Mr',
            },
            driverNumber: 'CATY123456789D04',
            mobileTelephone: '(926) 488-2327',
            primaryTelephone: '(890) 435-3560',
            secondaryTelephone: '(964) 501-3921',
            dateOfBirth: '1982-06-25',
            ethnicityCode: 'D',
            gender: 'M',
          },
          business: {
            businessAddress: {
              addressLine1: '57 B+E',
              addressLine2: 'Lefferts Avenue',
              addressLine3: 'Iran',
              postcode: 'SA73 0TT',
            },
            businessId: 7872,
            businessName: 'Irack',
            telephone: '(806) 479-2387',
          },
          previousCancellation: [],
        },
        slotDetail: {
          duration: 57,
          slotId: 3445,
          start: moment().set({hour: 16, minute: 16, second: 0, millisecond: 0}).format('YYYY-MM-DDTHH:mm:ss'),
        },
        testCentre: {
          centreId: 3033,
          centreName: 'Test DA',
          costCode: 'A1234',
        },
        vehicleTypeCode: 'C',
        vehicleSlotTypeCode: 7,
        examinerVisiting: false,
      },
    },
  ];

  return bookings.filter(slot => examinerId.includes(slot.examinerId));
};
