name: CI

on:
  pull_request:
    branches:
      - develop
      - 'release-**'

jobs:
  runs-ci:
    uses: dvsa/des-workflow-actions/.github/workflows/ci-backend.yaml@sonar
    secrets:
      DES_ACCESS_TOKEN: ${{ secrets.DES_ACCESS_TOKEN }}
      DES_SONARQUBE_TOKEN: ${{ secrets.DES_SONARQUBE_TOKEN }}
      DES_SONARQUBE_HOST_URL: ${{ secrets.DES_SONARQUBE_HOST_URL }}
